# Pandas cheat sheet

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [2]:
import pandas as pd

In [3]:
# specify the value of each column

df = pd.DataFrame({"a" : [4, 5, 6],
                   "b" : [7, 8, 9],
                   "c" : [10, 11, 12]},
                  index = [1, 2, 3])

In [4]:
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [5]:
# Specify values for each row.
df = pd.DataFrame([[4, 7, 10],
                   [5, 8, 11],
                   [6, 9, 12]],
                  index=[1, 2, 3],
                  columns=['a', 'b', 'c'])

In [6]:
df.shape

(3, 3)

In [7]:
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [8]:
df.iloc[0]

a     4
b     7
c    10
Name: 1, dtype: int64

In [9]:
df.iloc[:, [1]]

   b
1  7
2  8
3  9

In [12]:
df.iloc[:, [1,2]]

   b   c
1  7  10
2  8  11
3  9  12

In [15]:
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [13]:
df.loc[df['a'] > 10]

Empty DataFrame
Columns: [a, b, c]
Index: []

In [16]:
df.loc[df['a'] > 5]['a']

3    6
Name: a, dtype: int64

In [17]:
# Access single value by index
df.iat[1, 2]

11

In [19]:
# Access single value by label
df.at[1, 'a']

4

In [20]:
df['a'].nunique()
# of distinct values in a column.

3

In [21]:
df.describe()

         a    b     c
count  3.0  3.0   3.0
mean   5.0  8.0  11.0
std    1.0  1.0   1.0
min    4.0  7.0  10.0
25%    4.5  7.5  10.5
50%    5.0  8.0  11.0
75%    5.5  8.5  11.5
max    6.0  9.0  12.0

In [22]:
df.sum()

a    15
b    24
c    33
dtype: int64

In [23]:
# Drop rows with any column having NA/null data
df.dropna()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [24]:
# Replace all NA/null data with value.
df.fillna(0)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12